/* eq_numbers.asm  
 *equal between N numbers: X1=X2= ... =Xn return #t or #f
 *args - 1 or more 
 *special (= 5) -> #t
 */
 
 EQNUMBERS:
 
	PUSH(FP);
	MOV(FP,SP);		/*OPEN NEW FRAME*/
	PUSH(R1);
	PUSH(R2);
	MOV(R1,FPARG(1)); /*SAVE THE ARGUMENTS NUMBER TO R1*/
	MOV(R2,FPARG(2)); 
	CMP(R1,IMM(0));
	JUMP_GT(EQ_NUMBERS_LOOP_EQ_NUMBERS);
	SHOW("bad input argument for = need to be one or more arguments. R1 is the num of arguments",R1);
	HALT;
 EQ_NUMBERS_LOOP_EQ_NUMBERS:
	CMP(R1,IMM(1)); /*BECAUSE R2 GET ALREADY THE FGPARG(2) SO I DONT NEED TO SHECK IF FPARG(2)=FPARG(2)*/
	JUMP_EQ(EQ_NUMBERS_LOOP_END_EQ_NUMBERS);
	
	CMP(IND(FPARG(1+R1)),T_INTEGER); /*CHECK IF THE ARGUMENT IN R1 PLACE IS INTEGER*/
	JUMP_EQ(ARG_IS_OK_EQ_NUMBERS);
	SHOW("The argumen in the R1 place is not integer. print FPARG(1+R1)",FPARG(1+R1));
	HALT;
 ARG_IS_OK_EQ_NUMBERS:	
	CMP(INDD(R2,1),INDD(FPARG(1+R1),1)); /*COMPERE THE FIRST ARG VALUE WHIT ALL THE OTHERS ARGS VALUES NEED TO BE THE SAME*/
	JUMP_NE(ANS_FALSE_EQ_NUMBERS);
	DECR(R1);
	JUMP(EQ_NUMBERS_LOOP_EQ_NUMBERS);
 EQ_NUMBERS_LOOP_END_EQ_NUMBERS:
	MOV(R0,IMM(5)); /*THE LOOP IS ENDED END ALL ARGS IS TE SAME SO NEED TO RETURN #t*/
	JUMP(END_EQ_NUMBERS_EQ_NUMBERS);
 ANS_FALSE_EQ_NUMBERS:
	MOV(R0,IMM(3)); /*IF I GET HERE SO I NEED TO RETURN #f IMM(3)=FALSE*/
 END_EQ_NUMBERS_EQ_NUMBERS:	
	POP(R2);
	POP(R1);
	MOV(SP,FP);
	POP(FP);
 RETURN; 