/* integer_to_char.asm
 * converts sob_integer  to sob_char 
*/

INTEGERTOCHAR:

	PUSH(FP);
	MOV(FP, SP);
	PUSH(R1);
	CMP(FPARG(1),IMM(1)); /*<- ARGUMENT NUMBER (NEED TO BE 1)*/
	JUMP_EQ(ANOTHER_CHECK_INTEGER_TO_CHAR)
	SHOW("for INTEGER_TO_CHAR procedure need to be 1 argument you send (print ->)",FPARG(1));
	HALT;
ANOTHER_CHECK_INTEGER_TO_CHAR:	
    MOV(R1,FPARG(2));
	CMP(IND(R1),T_INTEGER); /*<- ARGUMENT NEED TO BE SOB_INTEGER*/
	JUMP_EQ(ANOTHER_CHECK_2_INTEGER_TO_CHAR)
	SHOW("THE ARGUMENT NEED TO BE T_INTEGER YOU SEND(print ->)",IND(R1));
	HALT;
ANOTHER_CHECK_2_INTEGER_TO_CHAR:	
	CMP(INDD(R1,1),IMM(0)); /*<- ARGUMENT NEED TO BE >0*/
	JUMP_GE(ANOTHER_CHECK_3_INTEGER_TO_CHAR)
	SHOW("THE ARGUMENT NEED TO BE T_INTEGER >0 YOU SEND(print ->)",INDD(R1,1));
	HALT;
ANOTHER_CHECK_3_INTEGER_TO_CHAR:	
	MOV(R1, INDD(R1, 1));
	PUSH(R1);
	CALL(MAKE_SOB_CHAR);
	DROP(1);
	POP(R1);
	MOV(SP,FP);
	POP(FP);
RETURN;