/* plus.asm  
 *add N numbers: X1+X2+ ... + XN
 */
 
 PLUS:
 
	PUSH(FP);
	MOV(FP,SP);		/*OPEN NEW FRAME*/
	
	PUSH(R1);
	MOV(R0,IMM(0));  /*R0 WILL BE THE ANS I RESET IT TO 0 FIRST*/
	MOV(R1,FPARG(1)); /*SAVE THE ARGUMENTS NUMBER TO R1*/
 PLUS_LOOP:
	CMP(R1,IMM(0));
	JUMP_EQ(PLUS_LOOP_END);
	
	CMP(IND(FPARG(1+R1)),T_INTEGER); /*CHECK IF THE ARGUMENT IN R1 PLACE IS INTEGER*/
	JUMP_EQ(ARG_IS_OK_PLUS);
	SHOW("The argumen in the R1 place is not integer. print FPARG(1+R1)",FPARG(1+R1));
	HALT;
 ARG_IS_OK_PLUS:	
	ADD(R0,INDD(FPARG(1+R1),1)); /*ADD TO ANS THE THE VALUE OF THE SOB_INTEGER THAT IN FPARG(X)*/
	DECR(R1);
	JUMP(PLUS_LOOP);
 PLUS_LOOP_END:
	PUSH(R0);
	CALL(MAKE_SOB_INTEGER); /*NOW R0 POINT TO SOB_INTEGER THAT IS VALUE IS THE PLUS ANS*/
	DROP(1);
	POP(R1);
	MOV(SP,FP);
	POP(FP);
 RETURN; 