/* vector_set.asm
 * RECIVE pointer to a SOB_VECTOR number and new object, and replace the n'th ITEM in the new one

 */

 VECTOR_SET:
	  PUSH(FP);
	  MOV(FP, SP);

	  PUSH(R1);
	  PUSH(R2);
	  PUSH(R3);
	  CMP(FPARG(1),IMM(3)); /*NEED TO BE 3 ARGUMENT FOR THIS PROCEDURE*/
	  JUMP_EQ(ANOTHER_CHECK_VECTOR_SET);
	  SHOW("bad input argument for VECTOR_SET need to be 3 arguments. PRINT->",FPARG(1));
	  HALT;
 ANOTHER_CHECK_VECTOR_SET:
	  MOV(R1, FPARG(2)); /*R1<- THE VECTOR*/
	  MOV(R2, FPARG(3)); /*R2<- THE NUM */
	  MOV(R3,FPARG(4));  /*R3<- THE NEW OBJECT*/
	  CMP(IND(R1),T_VECTOR); /*CHECK IF ITS SOB_VECTOR*/
	  JUMP_EQ(ANOTHER_CHECK_2_VECTOR_SET);
	  SHOW("bad input THE FIRST ARGUMENT IS NOT A VECTOR. PRINT->",IND(R1));
	  HALT;
 ANOTHER_CHECK_2_VECTOR_SET:
	  CMP(IND(R2),T_INTEGER); /*CHECK IF ITS SOB_INTEGER*/
	  JUMP_EQ(ANOTHER_CHECK_3_VECTOR_SET);
	  SHOW("bad input THE SECOND ARGUMENT IS NOT SOB_INTEGER). PRINT->",IND(R2));
	  HALT;
 ANOTHER_CHECK_3_VECTOR_SET:	
	  CMP(INDD(R2,1),IMM(0)); /*CHECK IF the number  is <0 */
	  JUMP_GE(ANOTHER_CHECK_4_VECTOR_SET);
	  SHOW("bad input THE SECOND ARGUMENT NEED TO BE >0 . PRINT->",INDD(R2,1));
	  HALT;
 ANOTHER_CHECK_4_VECTOR_SET:
	  CMP(INDD(R2,1),INDD(R1,1)); /*CHECK IF the number  is < VECTOR length*/
	  JUMP_LT(ANOTHER_CHECK_5_VECTOR_SET);
	  SHOW("bad input THE SECOND ARGUMENT NEED TO BE  < (length VECTOR). PRINT->",INDD(R2,1));
	  HALT;
 ANOTHER_CHECK_5_VECTOR_SET:	  
	  ADD(R1, IMM(2));
	  ADD(R1, INDD(R2, 1));
	  MOV(IND(R1), R3);/*IND(R1) POINT TO THE N'TH OBJECT IN THE GIVEN VECTOR AND WE REPLACE THAT OBJECT WHITH THE NEW ONE IN R3*/
	  MOV(R0,IMM(2)); /*VECTOR-SET! RETURN VOID*/
	  POP(R3);
	  POP(R2);
	  POP(R1)
	  MOV(SP, FP);
	  POP(FP);
 RETURN;


